# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: cd frontend
    - run: npm i
    - run: npm run build --if-present
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        script: |
          # Replace these commands with your actual deployment steps
          scp -r frontend/build venkat@162.243.187.23:/var/www/sites/_work/mern-traversy-new/mern-traversy-new/frontend
          ssh venkat@162.243.187.23 "cd /var/www/sites/_work/mern-traversy-new/mern-traversy-new && pm2 restart 0"
